version: 0.0
os: linux
files:
  - source: /aws/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: aws/install_dependencies
      timeout: 300
      runas: root
    - location: aws/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: aws/stop_server
      timeout: 300
      runas: root