version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - python3 -m pip3 install --upgrade pip3
      - pip3 install flake8 pytest
  build:
    commands:
      - pytest -v
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: blackjack-latest