version: 0.2

phases:
  install:
    commands:
      - wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tar.xz
      - tar xJf Python-3.8.0.tar.xz
      - cd Python-3.8.0
      - ./configure
      - make
      - make install
  pre_build:
    commands:
      - pip3 install flake8 pytest
  build:
    commands:
      - pytest -v
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: blackjack-latest