version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -e .
      - pip install flake8 pytest
  build:
    commands:
      - pytest -v
  post_build:
    commands:
      - echo Build completed on `date`