version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
  build:
    commands:
      - python -m pytest -v
  post_build:
    commands:
      - python setup.py clean
      - echo Build completed on `date`
artifacts:
  files:
    - 'blackjack/*'
    - 'tests/*'
    - 'setup.py'
  name: blackjack-latest